version: '3.7'

services:
  snake-server:
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ../lib/server.js:/usr/src/app/server.js
    environment:
      NODE_ENV: development
      WAIT_HOSTS: mongodb_image:27017
    depends_on:
      - mongodb_image
    networks:
      - backend

  mongodb_image:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend

  snake-client:
    build:
      context: ..
      dockerfile: ./docker/ui/Dockerfile
    ports:
      - '80:80'
    volumes:
      - ../:/usr/share/nginx/html
    environment:
      - NODE_ENV=development  
    depends_on:
      - snake-server
    networks:
      - frontend

volumes:
  mongodb_data_container:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge