version: '3.7'

services:
  snake-server:
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb_image
    environment:
      WAIT_HOSTS: mongodb_image:27017
  mongodb_image:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:    