version: '3.7'

services:
  snake-server:
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    container_name: snake_server  
    ports:
      - '8080:8080'
    volumes:
      - ../server/db:/usr/src/app/db
      - ../server/index.js:/usr/src/app/index.js
      - ../server/package.json:/usr/src/app/package.json
      - ../server/settings.json:/usr/src/app/settings.json
    environment:
      WAIT_HOSTS: mongodb_image:27017
    depends_on:
      - mongodb_image
    networks:
      - backend

  mongodb_image:
    image: mongo:latest
    container_name: snake_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend

  snake-client:
    build:
      context: ..
      dockerfile: ./docker/ui/dev/Dockerfile
    container_name: snake_client  
    ports:
      - '80:80'
    volumes:
      - ../client/css:/usr/share/nginx/html/css
      - ../client/js:/usr/share/nginx/html/js
      - ../client/locales:/usr/share/nginx/html/locales
      - ../client/view:/usr/share/nginx/html/view
      - ../client/index.html:/usr/share/nginx/html/index.html
      - ../client/index.js:/usr/share/nginx/html/index.js
      - ../client/settings.json:/usr/share/nginx/html/settings.json
      - ../client/webpack.config.js:/usr/share/nginx/html/webpack.config.js
    environment:
      - ENV=dev
    depends_on:
      - snake-server
    networks:
      - frontend

volumes:
  mongodb_data_container:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge