version: '3.7'

services:
  snake-server:
    build:
      context: ..
      dockerfile: ./docker/app/Dockerfile
    container_name: snake_server  
    ports:
      - '8080:8080'
    environment:
      NODE_ENV: development
      WAIT_HOSTS: mongodb_image:27017
    depends_on:
      - mongodb_image
    networks:
      - backend

  mongodb_image:
    image: mongo:latest
    container_name: snake_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - backend

  snake-client:
    build:
      context: ..
      dockerfile: ./docker/ui/Dockerfile
    container_name: snake_client  
#    volumes:
#        - ./ui/snake.template:/etc/nginx/conf.d/default.conf
 #       - ./sslcert:/usr/cert
    ports:
      - '80:80'
      - '443:443'
    environment:
      ENV: prod
      WAIT_HOSTS: snake-server:8080
    depends_on:
      - snake-server
    links:
      - snake-server
    restart: always
    networks:
      - frontend

volumes:
  mongodb_data_container:

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
